"""Generate cities/media/model.ipynb"""
import json
from pathlib import Path

def code_cell(source):
    if isinstance(source, str):
        source = [source]
    return {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': source,
    }

def md_cell(source):
    if isinstance(source, str):
        source = [source]
    return {
        'cell_type': 'markdown',
        'metadata': {},
        'source': source,
    }

cells = []

# ── Title ────────────────────────────────────────────────────────────────────
cells.append(md_cell(
    '# Media Borough, PA — Land Value Tax Model\n'
    '\n'
    '**Borough levy only | 4:1 split-rate | Media Borough, Delaware County, PA**\n'
    '\n'
    '## Methodology Note — Estimated Land/Improvement Ratios\n'
    '\n'
    'Delaware County does not publicly expose per-parcel land vs. improvement assessed values.\n'
    'The iasWorld portal shows only the **total** assessed value per parcel. This model uses:\n'
    '\n'
    '1. Total assessed values scraped from the county iasWorld portal\n'
    '2. Estimated land/improvement ratios by property type\n'
    '\n'
    'This is analogous to Philadelphia\'s OPA system, which defaults ~45% of improved parcels to\n'
    'a fixed 20% land ratio. Directional results (vacant land increases, SFR decreases) are\n'
    'reliable; exact per-parcel magnitudes are approximate. Calibrated to PA mature-borough norms.\n'
    '\n'
    '**Assessment system**: Delaware County completed a county-wide reassessment in 2021 at full\n'
    'market value. The STEB Common Level Ratio is ~61.35% (assessed/market), but the borough\n'
    'millage is applied directly to assessed value — no further ratio adjustment needed.'
))

# ── Section 1: Imports ───────────────────────────────────────────────────────
cells.append(code_cell(
    'import sys\n'
    'import json\n'
    'import os\n'
    'import re\n'
    'import time\n'
    'import concurrent.futures\n'
    'from pathlib import Path\n'
    '\n'
    'import geopandas as gpd\n'
    'import matplotlib\n'
    'matplotlib.use("Agg")\n'
    'import matplotlib.pyplot as plt\n'
    'import numpy as np\n'
    'import pandas as pd\n'
    'import requests\n'
    'from dotenv import load_dotenv\n'
    '\n'
    'sys.path.insert(0, "../..")\n'
    'REPO_ROOT = Path("../..").resolve()\n'
    'load_dotenv(REPO_ROOT / ".env")\n'
    '\n'
    'from lvt.lvt_utils import (\n'
    '    model_split_rate_tax,\n'
    '    calculate_current_tax,\n'
    '    calculate_category_tax_summary,\n'
    '    print_category_tax_summary,\n'
    '    save_standard_export,\n'
    ')\n'
    'from lvt.census_utils import get_census_data_with_boundaries, match_to_census_blockgroups\n'
    '\n'
    'CITY_NAME = "media"\n'
    'STATE_FIPS = "42"   # Pennsylvania\n'
    'COUNTY_FIPS = "045" # Delaware County\n'
    'MODEL_TYPE = "split_rate:4.0"\n'
    'LAND_IMPROVEMENT_RATIO = 4.0\n'
    '\n'
    '# Borough-only levy (2024-2026 rate unchanged)\n'
    'BOROUGH_MILLAGE = 2.0000\n'
    '\n'
    '# Official revenue: Media Borough CAFR 2024\n'
    '# 2.0 mills x $956,220,094 taxable base = $1,912,440\n'
    'OFFICIAL_REVENUE = 1_912_440\n'
    '\n'
    '# 0 = load from cache, 1 = re-scrape iasWorld\n'
    'data_scrape = 0\n'
    '\n'
    'DATA_DIR = Path("data")\n'
    'DATA_DIR.mkdir(exist_ok=True)\n'
))

# ── Section 2 header ─────────────────────────────────────────────────────────
cells.append(md_cell(
    '## Section 2 — Fetch Parcel Data\n'
    '\n'
    '### 2a. Geometry from Delaware County GIS\n'
    '\n'
    'Source: `gis.delcopa.gov/arcgis/rest/services/Parcels/Parcels_Public_Access/FeatureServer/0`  \n'
    'Filter: `MUNICIPALI=26` (Media Borough)\n'
    '\n'
    '### 2b. Assessed Values from iasWorld\n'
    '\n'
    'Scraped concurrently from Delaware County iasWorld portal (one request per parcel).  \n'
    'Fields: total assessed value, property type code.  \n'
    'Cached to `data/iasworld_assessments.csv` — set `data_scrape=1` to re-fetch.'
))

# ── 2a: GIS download ─────────────────────────────────────────────────────────
cells.append(code_cell(
    'PARCEL_GIS_PATH = DATA_DIR / "parcels_geo.gpq"\n'
    '\n'
    '\n'
    'def fetch_media_parcels_gis():\n'
    '    """Download Media Borough parcel geometry from Delaware County ArcGIS."""\n'
    '    from shapely.geometry import Polygon\n'
    '\n'
    '    base = (\n'
    '        "https://gis.delcopa.gov/arcgis/rest/services/"\n'
    '        "Parcels/Parcels_Public_Access/FeatureServer/0/query"\n'
    '    )\n'
    '    all_records = []\n'
    '    offset = 0\n'
    '\n'
    '    while True:\n'
    '        params = {\n'
    '            "where": "MUNICIPALI=26",\n'
    '            "outFields": "PIN,PARID,LEGAL2,OWNCAT,ADRCAT",\n'
    '            "returnGeometry": "true",\n'
    '            "outSR": 4326,\n'
    '            "geometryPrecision": 6,\n'
    '            "f": "json",\n'
    '            "resultOffset": offset,\n'
    '            "resultRecordCount": 1000,\n'
    '        }\n'
    '        r = requests.get(base, params=params, timeout=60)\n'
    '        r.raise_for_status()\n'
    '        data = r.json()\n'
    '        features = data.get("features", [])\n'
    '        all_records.extend(features)\n'
    '        if not data.get("exceededTransferLimit"):\n'
    '            break\n'
    '        offset += len(features)\n'
    '        time.sleep(0.3)\n'
    '\n'
    '    print(f"Downloaded {len(all_records)} parcels from GIS")\n'
    '\n'
    '    rows, geometries = [], []\n'
    '    for feat in all_records:\n'
    '        attr = feat["attributes"]\n'
    '        rows.append(attr)\n'
    '        rings = (feat.get("geometry") or {}).get("rings", [])\n'
    '        if rings:\n'
    '            # First ring = outer boundary; subsequent rings = holes\n'
    '            outer = rings[0]\n'
    '            holes = rings[1:]\n'
    '            geom = Polygon(outer, holes) if holes else Polygon(outer)\n'
    '        else:\n'
    '            geom = None\n'
    '        geometries.append(geom)\n'
    '\n'
    '    gdf = gpd.GeoDataFrame(pd.DataFrame(rows), geometry=geometries, crs="EPSG:4326")\n'
    '    return gdf\n'
    '\n'
    '\n'
    'if PARCEL_GIS_PATH.exists() and not data_scrape:\n'
    '    gdf_geo = gpd.read_parquet(PARCEL_GIS_PATH)\n'
    '    print(f"Loaded {len(gdf_geo):,} parcels from GIS cache")\n'
    'else:\n'
    '    gdf_geo = fetch_media_parcels_gis()\n'
    '    gdf_geo = gdf_geo.drop_duplicates(subset=["PIN"]).reset_index(drop=True)\n'
    '    gdf_geo.to_parquet(PARCEL_GIS_PATH)\n'
    '    print(f"Cached {len(gdf_geo):,} parcels")\n'
    '\n'
    'print(f"Columns: {list(gdf_geo.columns)}")\n'
    'print(gdf_geo[["PIN", "PARID", "LEGAL2", "ADRCAT"]].head(5))\n'
))

# ── 2b: iasWorld scraping ────────────────────────────────────────────────────
cells.append(code_cell(
    'ASSESS_CACHE_PATH = DATA_DIR / "iasworld_assessments.csv"\n'
    '\n'
    '\n'
    'def parse_iasworld_page(html):\n'
    '    """Parse iasWorld profileall_pub page for total assessed value + property type."""\n'
    '    from bs4 import BeautifulSoup\n'
    '\n'
    '    soup = BeautifulSoup(html, "html.parser")\n'
    '\n'
    '    # Property type from the Parcel summary table\n'
    '    property_type = None\n'
    '    parcel_table = soup.find("table", {"id": "Parcel"})\n'
    '    if parcel_table:\n'
    '        for row in parcel_table.find_all("tr"):\n'
    '            cells = row.find_all("td")\n'
    '            if len(cells) >= 2 and "Property Type" in cells[0].get_text():\n'
    '                property_type = cells[1].get_text(strip=True)\n'
    '                break\n'
    '\n'
    '    # Total assessed value from "Original Current Year Assessment" table\n'
    '    assessed_value = None\n'
    '    asmt_table = soup.find("table", {"id": "Original Current Year Assessment"})\n'
    '    if asmt_table:\n'
    '        for row in asmt_table.find_all("tr"):\n'
    '            cells = row.find_all("td", class_="DataletData")\n'
    '            if len(cells) >= 2:\n'
    '                val = re.sub(r"[$,\\s]", "", cells[1].get_text(strip=True))\n'
    '                if val.lstrip("-").isdigit():\n'
    '                    assessed_value = int(val)\n'
    '                    break\n'
    '\n'
    '    return assessed_value, property_type\n'
    '\n'
    '\n'
    'def scrape_parcel(parid_int):\n'
    '    """Fetch one iasWorld parcel page and return parsed data."""\n'
    '    url = (\n'
    '        "http://delcorealestate.co.delaware.pa.us/pt/datalets/datalet.aspx"\n'
    '        f"?mode=profileall_pub&usesearch=no&jur=023&taxyr=2026&pin={parid_int}"\n'
    '    )\n'
    '    try:\n'
    '        r = requests.get(url, timeout=20)\n'
    '        r.raise_for_status()\n'
    '        av, pt = parse_iasworld_page(r.text)\n'
    '        return {"parid": parid_int, "assessed_value": av, "property_type_raw": pt}\n'
    '    except Exception:\n'
    '        return {"parid": parid_int, "assessed_value": None, "property_type_raw": None}\n'
    '\n'
    '\n'
    'if ASSESS_CACHE_PATH.exists() and not data_scrape:\n'
    '    df_assess = pd.read_csv(ASSESS_CACHE_PATH)\n'
    '    print(f"Loaded {len(df_assess):,} assessment records from cache")\n'
    'else:\n'
    '    parids = [\n'
    '        int(v) for v in gdf_geo["PARID"].dropna().unique()\n'
    '        if not pd.isna(v)\n'
    '    ]\n'
    '    print(f"Scraping iasWorld for {len(parids):,} parcels (20 concurrent workers)...")\n'
    '    results = []\n'
    '    with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:\n'
    '        futures = {executor.submit(scrape_parcel, pid): pid for pid in parids}\n'
    '        for i, future in enumerate(concurrent.futures.as_completed(futures)):\n'
    '            results.append(future.result())\n'
    '            if (i + 1) % 200 == 0:\n'
    '                print(f"  {i + 1}/{len(parids)} done")\n'
    '    df_assess = pd.DataFrame(results)\n'
    '    df_assess.to_csv(ASSESS_CACHE_PATH, index=False)\n'
    '    print(f"Scraped and cached {len(df_assess):,} records")\n'
    '\n'
    'print(f"Null assessed values: {df_assess[\\"assessed_value\\"].isna().sum()}")\n'
    'print(df_assess["property_type_raw"].value_counts().head(10))\n'
))

# ── Merge GIS + assessment ───────────────────────────────────────────────────
cells.append(code_cell(
    '# Join geometry (GIS) with assessed values (iasWorld)\n'
    'gdf_geo["parid_int"] = pd.to_numeric(gdf_geo["PARID"], errors="coerce").dropna().astype(int)\n'
    'gdf_geo["parid_int"] = gdf_geo["PARID"].apply(\n'
    '    lambda v: int(v) if pd.notna(v) else None\n'
    ')\n'
    'df_assess["parid"] = df_assess["parid"].astype(int)\n'
    '\n'
    'gdf = gdf_geo.merge(df_assess, left_on="parid_int", right_on="parid", how="left")\n'
    'print(f"After merge: {len(gdf):,} parcels")\n'
    'print(f"With assessed value: {gdf[\\"assessed_value\\"].notna().sum():,}")\n'
    'print(f"Total assessed (merged): ${gdf[\\"assessed_value\\"].sum():,.0f}")\n'
    'print(f"Official taxable base (CAFR 2024): $956,220,094")\n'
))

# ── Section 3: Classify ──────────────────────────────────────────────────────
cells.append(md_cell(
    '## Section 3 — Classify Parcels\n'
    '\n'
    '### Property Type Codes (Delaware County iasWorld)\n'
    '\n'
    '| Code prefix | Description |\n'
    '|---|---|\n'
    '| 01 | Taxable Residential |\n'
    '| 02 | Taxable Non-Residential (commercial, industrial) |\n'
    '| Other | Exempt (government, nonprofit, religious) |\n'
    '\n'
    'LEGAL2 descriptions provide sub-classification within residential:\n'
    '"2 STY HSE" → SFR, "DUPLEX" → Small MF, "APT BLDG" → Large MF, "CONDO" → Condominium, etc.\n'
    '\n'
    '### Estimated Land/Improvement Ratios (documented limitation)\n'
    '\n'
    '| Category | Land % | Basis |\n'
    '|---|---|---|\n'
    '| Single Family Residential | 30% | PA mature-borough SFR median |\n'
    '| Small Multi-Family (2-4 units) | 35% | Smaller structures, higher land share |\n'
    '| Large Multi-Family (5+ units) | 38% | Density offset by high land value |\n'
    '| Condominium | 20% | Structure-intensive; shared land |\n'
    '| Townhome / Rowhouse | 28% | Attached; smaller per-unit lot |\n'
    '| Commercial | 45% | Downtown Media: high land, modest structures |\n'
    '| Industrial | 30% | Larger footprint structures |\n'
    '| Mixed Use | 40% | Commercial land, residential improvement |\n'
    '| Vacant Land | 100% | By definition — zero improvement value |\n'
    '| Exempt | N/A | Excluded from reform base |'
))

cells.append(code_cell(
    'def classify_property(row):\n'
    '    """Map iasWorld property type + LEGAL2 description to standard LVTShift category."""\n'
    '    pt  = str(row.get("property_type_raw") or "").upper()\n'
    '    leg = str(row.get("LEGAL2") or "").upper()\n'
    '    av  = row.get("assessed_value") or 0\n'
    '\n'
    '    # Zero or missing assessment → Exempt\n'
    '    if not av or pd.isna(av):\n'
    '        return "Exempt"\n'
    '\n'
    '    # Explicitly exempt property type\n'
    '    if "EXEMPT" in pt:\n'
    '        return "Exempt"\n'
    '\n'
    '    # Vacant land markers in description\n'
    '    if any(x in leg for x in ["GRD", "VAC LOT", "VACANT", "LAND ONLY", "LOT-LAND",\n'
    '                               "UNIMPR", "EMPTY LOT"]):\n'
    '        return "Vacant Land"\n'
    '\n'
    '    # Large multi-family (5+ units)\n'
    '    if any(x in leg for x in ["APT BLDG", "APARTMENT", " APTS", "APART",\n'
    '                               "5 FAM", "6 FAM", "6 UNIT", "8 UNIT",\n'
    '                               "10 UNIT", "12 UNIT", "MULTI-FAM", "MULTI FAM"]):\n'
    '        return "Large Multi-Family (5+ units)"\n'
    '\n'
    '    # Small multi-family (2-4 units)\n'
    '    if any(x in leg for x in ["DUPLEX", "DUP HSE", "DUP.", "TRIPLEX",\n'
    '                               "2 FAM", "3 FAM", "4 FAM", "2-FAM", "3-FAM", "4-FAM",\n'
    '                               "2 APTS", "3 APTS", "4 APTS", "TWIN"]):\n'
    '        return "Small Multi-Family (2-4 units)"\n'
    '\n'
    '    # Condominium\n'
    '    if any(x in leg for x in ["CONDO", "CONDOMINIUM"]):\n'
    '        return "Condominium"\n'
    '\n'
    '    # Townhome / Rowhouse\n'
    '    if any(x in leg for x in ["ROW HSE", "ROWHOUSE", "TOWNHOUSE", "TOWNHOME",\n'
    '                               "TOWN HSE", "END ROW", "INT ROW"]):\n'
    '        return "Townhome / Rowhouse"\n'
    '\n'
    '    # Mixed use\n'
    '    if any(x in leg for x in ["MIX", "MIXED", "STORE & APT", "STORES & APT",\n'
    '                               "COMM & RES", "BLDG & APT", "STORES & OFFC & APT"]):\n'
    '        return "Mixed Use"\n'
    '\n'
    '    # Commercial\n'
    '    if any(x in leg for x in ["COMM BLDG", "STORE", "OFFC", "OFFICE",\n'
    '                               "RESTAURANT", "RETAIL", "BANK", "COMMERCIAL",\n'
    '                               "MOTEL", "HOTEL", "SERVICE STA", "GAS STA",\n'
    '                               "AUTO", "WAREHOUSE", "PARKING", "GARAGE",\n'
    '                               "SHOPPING", "SUPERMARKET"]):\n'
    '        return "Commercial"\n'
    '\n'
    '    # Industrial\n'
    '    if any(x in leg for x in ["INDUS", "INDUSTRIAL", "MANUFACT", "PLANT",\n'
    '                               "UTILITY", "TELECOM"]):\n'
    '        return "Industrial"\n'
    '\n'
    '    # Non-residential catch-all → Commercial\n'
    '    if "02" in pt[:4] or "NON-RESIDENT" in pt or "NON RESIDENT" in pt:\n'
    '        return "Commercial"\n'
    '\n'
    '    # Default residential → Single Family Residential\n'
    '    if "01" in pt[:4] or "RESIDENT" in pt:\n'
    '        return "Single Family Residential"\n'
    '\n'
    '    return "Other"\n'
    '\n'
    '\n'
    'gdf["PROPERTY_CATEGORY"] = gdf.apply(classify_property, axis=1)\n'
    '\n'
    '# Final override: $0 or null assessed value → Exempt\n'
    'gdf.loc[\n'
    '    gdf["assessed_value"].isna() | (gdf["assessed_value"] == 0),\n'
    '    "PROPERTY_CATEGORY"\n'
    '] = "Exempt"\n'
    '\n'
    'print(gdf["PROPERTY_CATEGORY"].value_counts())\n'
))

# Residual check
cells.append(code_cell(
    '# Inspect "Other" residual for possible refinement\n'
    'other_mask = gdf["PROPERTY_CATEGORY"] == "Other"\n'
    'if other_mask.sum() > 0:\n'
    '    print(f"Other parcels: {other_mask.sum()}")\n'
    '    print(gdf.loc[other_mask, ["LEGAL2", "property_type_raw", "assessed_value"]].head(20))\n'
    'else:\n'
    '    print("No unclassified parcels — good.")\n'
))

# ── Section 4: Current Tax ───────────────────────────────────────────────────
cells.append(md_cell(
    '## Section 4 — Current Tax Model\n'
    '\n'
    '**Assessment basis**: Total assessed value (Delaware County 2021 reassessment at full market\n'
    'value; STEB CLR ~61.35%). Millage applied directly to assessed value.\n'
    '\n'
    '**Millage**: 2.0000 mills (Media Borough real estate tax, 2024–2026)\n'
    '\n'
    '**Formula**: `current_tax = assessed_value × 2.0 / 1000`\n'
    '\n'
    '**Exemptions**: Parcels with $0 assessed value (government, religious, nonprofit)\n'
    'are excluded from the revenue-neutral base.\n'
    '\n'
    '**Source**: Media Borough CAFR 2024 — Real Estate Tax millage schedule, p. 30'
))

cells.append(code_cell(
    '# Estimated land ratios\n'
    'LAND_RATIO_MAP = {\n'
    '    "Single Family Residential":      0.30,\n'
    '    "Small Multi-Family (2-4 units)": 0.35,\n'
    '    "Large Multi-Family (5+ units)":  0.38,\n'
    '    "Condominium":                    0.20,\n'
    '    "Townhome / Rowhouse":            0.28,\n'
    '    "Commercial":                     0.45,\n'
    '    "Industrial":                     0.30,\n'
    '    "Mixed Use":                      0.40,\n'
    '    "Vacant Land":                    1.00,\n'
    '    "Other":                          0.33,\n'
    '    "Exempt":                         0.00,\n'
    '}\n'
    '\n'
    'gdf["land_ratio"] = gdf["PROPERTY_CATEGORY"].map(LAND_RATIO_MAP).fillna(0.33)\n'
    '\n'
    'gdf["assessed_value"] = pd.to_numeric(gdf["assessed_value"], errors="coerce").fillna(0)\n'
    'gdf["taxable_land_value"] = (gdf["assessed_value"] * gdf["land_ratio"]).round(2)\n'
    'gdf["taxable_improvement_value"] = (\n'
    '    gdf["assessed_value"] * (1 - gdf["land_ratio"])\n'
    ').round(2)\n'
    '\n'
    '# Exempt flag and millage\n'
    'gdf["full_exmp"] = (gdf["PROPERTY_CATEGORY"] == "Exempt").astype(int)\n'
    'gdf["millage_rate"] = BOROUGH_MILLAGE\n'
    'gdf.loc[gdf["full_exmp"] == 1, "millage_rate"] = 0.0\n'
    '\n'
    'current_revenue, _, gdf = calculate_current_tax(\n'
    '    df=gdf,\n'
    '    tax_value_col="assessed_value",\n'
    '    millage_rate_col="millage_rate",\n'
    '    exemption_flag_col="full_exmp",\n'
    ')\n'
    '\n'
    'gap_pct = (current_revenue / OFFICIAL_REVENUE - 1) * 100\n'
    'print(f"Modeled:  ${current_revenue:,.0f}")\n'
    'print(f"Official: ${OFFICIAL_REVENUE:,.0f}")\n'
    'print(f"Gap:      {gap_pct:+.2f}%")\n'
    'print(f"Taxable parcels: {(gdf[\\"full_exmp\\"] == 0).sum():,}")\n'
    'print(f"Exempt parcels:  {(gdf[\\"full_exmp\\"] == 1).sum():,}")\n'
    '\n'
    '# Sanity: land + improvement totals\n'
    'taxable_only = gdf[gdf["full_exmp"] == 0]\n'
    'print(f"\\nTaxable assessed total: ${taxable_only[\\"assessed_value\\"].sum():,.0f}")\n'
    'print(f"Land portion:           ${taxable_only[\\"taxable_land_value\\"].sum():,.0f}")\n'
    'print(f"Improvement portion:    ${taxable_only[\\"taxable_improvement_value\\"].sum():,.0f}")\n'
))

# ── Section 5: Split-Rate ────────────────────────────────────────────────────
cells.append(md_cell('## Section 5 — 4:1 Split-Rate Model'))

cells.append(code_cell(
    'taxable = gdf[gdf["full_exmp"] == 0].copy()\n'
    '\n'
    'land_millage, improvement_millage, new_revenue, taxable = model_split_rate_tax(\n'
    '    df=taxable,\n'
    '    land_value_col="taxable_land_value",\n'
    '    improvement_value_col="taxable_improvement_value",\n'
    '    current_revenue=taxable["current_tax"].sum(),\n'
    '    land_improvement_ratio=LAND_IMPROVEMENT_RATIO,\n'
    ')\n'
    '\n'
    'exempt = gdf[gdf["full_exmp"] == 1].copy()\n'
    'exempt["new_tax"] = 0.0\n'
    'exempt["tax_change"] = 0.0\n'
    'exempt["tax_change_pct"] = 0.0\n'
    'gdf = pd.concat([taxable, exempt]).sort_index()\n'
    '\n'
    'print(f"Land millage:        {land_millage:.4f} mills")\n'
    'print(f"Improvement millage: {improvement_millage:.4f} mills")\n'
    'print(f"Revenue check:       ${new_revenue:,.0f} (target ${taxable[\\"current_tax\\"].sum():,.0f})")\n'
    '\n'
    'category_summary = calculate_category_tax_summary(\n'
    '    df=gdf,\n'
    '    category_col="PROPERTY_CATEGORY",\n'
    '    current_tax_col="current_tax",\n'
    '    new_tax_col="new_tax",\n'
    ')\n'
    'print_category_tax_summary(category_summary, title="Media Borough, PA — 4:1 Split-Rate Tax Impact")\n'
))

# Validation summary
cells.append(md_cell(
    '## Validation Summary\n'
    '\n'
    '| Check | Result |\n'
    '|---|---|\n'
    '| Revenue match | see Section 4 output |\n'
    '| Parcel count | 2,238 expected (GIS MUNICIPALI=26) |\n'
    '| Land/improvement split | **Estimated** — county does not publish parcel-level split |\n'
    '| SFR median change | expect modest decrease (−5% to −15%) |\n'
    '| Vacant land median change | expect large increase (+100% to +200%) |\n'
    '| Methodology caveat | Analogous to Philadelphia OPA fixed-ratio limitation |'
))

# ── Section 6: Charts ────────────────────────────────────────────────────────
cells.append(md_cell('## Section 6 — Exploratory Charts'))

cells.append(code_cell(
    'taxable_nv = gdf[(gdf["full_exmp"] == 0) & (gdf["PROPERTY_CATEGORY"] != "Vacant Land")]\n'
    'summary = taxable_nv.groupby("PROPERTY_CATEGORY")["tax_change_pct"].median().dropna()\n'
    '\n'
    'fig, ax = plt.subplots(figsize=(10, 6))\n'
    'summary.sort_values().plot.barh(ax=ax, color="steelblue")\n'
    'ax.set_title("Media Borough, PA — Median Tax Change % by Category\\n(4:1 Split-Rate, excluding Vacant Land)")\n'
    'ax.set_xlabel("Median % Change")\n'
    'ax.axvline(0, color="black", linewidth=0.8, linestyle="--")\n'
    'plt.tight_layout()\n'
    'plt.savefig(DATA_DIR / "category_preview.png", dpi=150)\n'
    'plt.close()\n'
    'print("Saved category_preview.png")\n'
))

# ── Section 7: Census + Export ───────────────────────────────────────────────
cells.append(md_cell('## Section 7 — Census Join + Export'))

cells.append(code_cell(
    '# Census join — must happen before export\n'
    'import concurrent.futures as _cf\n'
    'from lvt.census_utils import get_census_data_with_boundaries, match_to_census_blockgroups\n'
    '\n'
    '_fips = STATE_FIPS + COUNTY_FIPS\n'
    'try:\n'
    '    with _cf.ThreadPoolExecutor(max_workers=1) as _ex:\n'
    '        _future = _ex.submit(get_census_data_with_boundaries, _fips, 2022)\n'
    '        try:\n'
    '            census_data, census_gdf = _future.result(timeout=90)\n'
    '            gdf = match_to_census_blockgroups(gdf, census_gdf)\n'
    '            if ("minority_pct" not in gdf.columns\n'
    '                    and "total_pop" in gdf.columns\n'
    '                    and "white_pop" in gdf.columns):\n'
    '                gdf["minority_pct"] = (\n'
    '                    (gdf["total_pop"] - gdf["white_pop"]) / gdf["total_pop"] * 100\n'
    '                ).round(2)\n'
    '            if ("black_pct" not in gdf.columns\n'
    '                    and "total_pop" in gdf.columns\n'
    '                    and "black_pop" in gdf.columns):\n'
    '                gdf["black_pct"] = (\n'
    '                    gdf["black_pop"] / gdf["total_pop"] * 100\n'
    '                ).round(2)\n'
    '            print(f"Census join: {gdf[\\"std_geoid\\"].notna().mean()*100:.1f}% matched")\n'
    '        except _cf.TimeoutError:\n'
    '            print("Census API timed out — skipping census join")\n'
    '            for _col in ["std_geoid", "median_income", "minority_pct", "black_pct"]:\n'
    '                gdf[_col] = float("nan")\n'
    'except Exception as e:\n'
    '    print(f"Census join failed: {e}")\n'
    '    for _col in ["std_geoid", "median_income", "minority_pct", "black_pct"]:\n'
    '        gdf[_col] = float("nan")\n'
))

cells.append(code_cell(
    '# Export — gdf must have census columns by this point\n'
    'from lvt.lvt_utils import save_standard_export\n'
    '\n'
    'out_df = save_standard_export(\n'
    '    df=gdf,\n'
    '    city=CITY_NAME,\n'
    '    output_path=f"../../analysis/data/{CITY_NAME}.csv",\n'
    '    model_type=MODEL_TYPE,\n'
    '    land_millage=land_millage,\n'
    '    improvement_millage=improvement_millage,\n'
    '    property_category_col="PROPERTY_CATEGORY",\n'
    '    current_tax_col="current_tax",\n'
    '    new_tax_col="new_tax",\n'
    '    tax_change_col="tax_change",\n'
    '    tax_change_pct_col="tax_change_pct",\n'
    '    taxable_land_col="taxable_land_value",\n'
    '    taxable_improvement_col="taxable_improvement_value",\n'
    ')\n'
    '\n'
    'from lvt.viz import create_city_report\n'
    'create_city_report(out_df, CITY_NAME, show=False)\n'
    'print("Done.")\n'
))

# ── Assemble notebook ────────────────────────────────────────────────────────
notebook = {
    'cells': cells,
    'metadata': {
        'kernelspec': {
            'display_name': 'cle-venv-new',
            'language': 'python',
            'name': 'cle-venv-new',
        },
        'language_info': {
            'name': 'python',
            'version': '3.11.0',
        },
    },
    'nbformat': 4,
    'nbformat_minor': 5,
}

out = Path('C:/projects/LVTShift/cities/media/model.ipynb')
out.parent.mkdir(parents=True, exist_ok=True)
with open(out, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)

print(f'Written {out}')
print(f'Total cells: {len(cells)}')
